version: '3'
services:
  app: 
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    tty: true 
    # docker-container内で標準入力への接続を行うため追加
    stdin_open: true
    command: 
      "bash -c 'rm -f tmp/pids/server.pid &&
      bundle &&
      bin/rails db:create db:migrate db:seed &&
      bundle exec rails server -b 0.0.0.0'"

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "3306:3306"